-- VersusLetra initial Supabase schema.
-- Run this in the Supabase SQL editor or through the Supabase CLI after linking
-- project pswwfrqperukfmrxccqr.

create extension if not exists "pgcrypto";

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null,
  achievements jsonb not null default '{}'::jsonb,
  games_played integer not null default 0 check (games_played >= 0),
  games_won integer not null default 0 check (games_won >= 0),
  high_score integer not null default 0 check (high_score >= 0),
  xp integer not null default 0 check (xp >= 0),
  level integer not null default 1 check (level >= 1),
  nick_color text not null default '#ff4757',
  selected_theme text not null default 'default',
  unlocked_items jsonb not null default '{"avatars":["👤"],"colors":["#ff4757"],"themes":["default"]}'::jsonb,
  selected_avatar text not null default '👤',
  avatar text,
  is_admin boolean not null default false,
  last_seen timestamptz,
  current_room text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_nickname_length check (char_length(btrim(nickname)) between 1 and 24),
  constraint profiles_nick_color_hex check (nick_color ~ '^#[0-9A-Fa-f]{6}$')
);

create unique index if not exists profiles_nickname_unique_lower
  on public.profiles (lower(nickname));

create index if not exists profiles_last_seen_idx on public.profiles (last_seen desc);
create index if not exists profiles_level_xp_idx on public.profiles (level desc, xp desc);

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create or replace function public.protect_profile_admin_flag()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() = 'service_role' then
    return new;
  end if;

  if tg_op = 'INSERT' then
    new.is_admin = false;
  else
    new.is_admin = old.is_admin;
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_protect_admin_flag on public.profiles;
create trigger profiles_protect_admin_flag
before insert or update on public.profiles
for each row execute function public.protect_profile_admin_flag();

create or replace function public.is_current_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and is_admin = true
  );
$$;

create table if not exists public.friends (
  user_id uuid not null references public.profiles(id) on delete cascade,
  friend_id uuid not null,
  created_at timestamptz not null default now(),
  constraint friends_pkey primary key (user_id, friend_id),
  constraint friends_friend_id_fkey foreign key (friend_id) references public.profiles(id) on delete cascade,
  constraint friends_no_self_follow check (user_id <> friend_id)
);

create index if not exists friends_friend_id_idx on public.friends (friend_id);

create table if not exists public.ranking (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null default 0 check (score >= 0),
  user_id uuid unique references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ranking_player_name_length check (char_length(btrim(player_name)) between 1 and 24)
);

create index if not exists ranking_score_idx on public.ranking (score desc, created_at asc);

drop trigger if exists ranking_set_updated_at on public.ranking;
create trigger ranking_set_updated_at
before update on public.ranking
for each row execute function public.set_updated_at();

create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  category_name text not null,
  status text not null default 'new',
  created_at timestamptz not null default now(),
  constraint suggestions_category_name_length check (char_length(btrim(category_name)) between 1 and 80)
);

create index if not exists suggestions_created_at_idx on public.suggestions (created_at desc);

create table if not exists public.game_settings (
  id integer primary key,
  custom_rewards jsonb not null default '{"avatars":[],"colors":[],"themes":[]}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.game_settings (id, custom_rewards)
values (1, '{"avatars":[],"colors":[],"themes":[]}'::jsonb)
on conflict (id) do nothing;

drop trigger if exists game_settings_set_updated_at on public.game_settings;
create trigger game_settings_set_updated_at
before update on public.game_settings
for each row execute function public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.friends enable row level security;
alter table public.ranking enable row level security;
alter table public.suggestions enable row level security;
alter table public.game_settings enable row level security;

drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public"
on public.profiles for select
to anon, authenticated
using (true);

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "friends_select_own" on public.friends;
create policy "friends_select_own"
on public.friends for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "friends_insert_own" on public.friends;
create policy "friends_insert_own"
on public.friends for insert
to authenticated
with check (user_id = auth.uid());

drop policy if exists "friends_delete_own" on public.friends;
create policy "friends_delete_own"
on public.friends for delete
to authenticated
using (user_id = auth.uid());

drop policy if exists "ranking_select_public" on public.ranking;
create policy "ranking_select_public"
on public.ranking for select
to anon, authenticated
using (true);

drop policy if exists "ranking_insert_public" on public.ranking;
create policy "ranking_insert_public"
on public.ranking for insert
to anon, authenticated
with check (user_id is null or user_id = auth.uid());

drop policy if exists "ranking_update_own" on public.ranking;
create policy "ranking_update_own"
on public.ranking for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

drop policy if exists "suggestions_insert_public" on public.suggestions;
create policy "suggestions_insert_public"
on public.suggestions for insert
to anon, authenticated
with check (user_id is null or user_id = auth.uid());

drop policy if exists "suggestions_select_admin" on public.suggestions;
create policy "suggestions_select_admin"
on public.suggestions for select
to authenticated
using (public.is_current_admin());

drop policy if exists "game_settings_select_public" on public.game_settings;
create policy "game_settings_select_public"
on public.game_settings for select
to anon, authenticated
using (true);

drop policy if exists "game_settings_insert_admin" on public.game_settings;
create policy "game_settings_insert_admin"
on public.game_settings for insert
to authenticated
with check (public.is_current_admin());

drop policy if exists "game_settings_update_admin" on public.game_settings;
create policy "game_settings_update_admin"
on public.game_settings for update
to authenticated
using (public.is_current_admin())
with check (public.is_current_admin());

grant usage on schema public to anon, authenticated;
grant select on public.profiles to anon, authenticated;
grant insert, update on public.profiles to authenticated;
grant select, insert, update on public.ranking to anon, authenticated;
grant select, insert on public.suggestions to anon, authenticated;
grant select, insert, update on public.game_settings to anon, authenticated;
grant select, insert, delete on public.friends to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
